import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, writeFileSync, copyFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
if (!process.env.PACKED_PROOF_CHILD) {
  const root = mkdtempSync(join(tmpdir(), 'gentle-packed-'));
  const consumer = join(root, 'consumer');
  for (const dir of ['consumer', 'home', 'tmp', 'config', 'agent/agents', 'models', 'cache']) mkdirSync(join(root, dir), {recursive:true});
  const env = {...process.env, HOME:join(root,'home'), USERPROFILE:join(root,'home'), TMPDIR:join(root,'tmp'), TMP:join(root,'tmp'), TEMP:join(root,'tmp'), XDG_CONFIG_HOME:join(root,'config'), XDG_CACHE_HOME:join(root,'cache'), npm_config_cache:join(root,'cache/npm'), npm_config_ignore_scripts:'true', GENTLE_PI_SKIP_GENTLE_AI_INSTALL:'1', PI_CODING_AGENT_DIR:join(root,'agent'), GENTLE_PI_AGENT_HOME:join(root,'agent'), GENTLE_PI_CONFIG_HOME:join(root,'models'), NODE_PATH:'', PACKED_PROOF_CHILD:'1'};
  function run(command, args, cwd) {
    const result = spawnSync(command, args, {cwd, env, encoding:'utf8', timeout:240000, maxBuffer:8*1024*1024});
    if (result.error || result.status !== 0) throw new Error(JSON.stringify({command,args,status:result.status,error:result.error?.message,stdout:result.stdout,stderr:result.stderr}));
    return result.stdout;
  }
  const pack = JSON.parse(run('npm', ['pack','--ignore-scripts','--json','--pack-destination',root], process.cwd()));
  const tarball = join(root, pack[0].filename);
  env.PROOF_SHA256 = createHash('sha256').update(readFileSync(tarball)).digest('hex');
  env.PROOF_COMMIT = run('git',['rev-parse','HEAD'],process.cwd()).trim();
  writeFileSync(join(consumer,'package.json'), JSON.stringify({private:true,type:'module',dependencies:{'gentle-pi':'file:'+tarball,'@earendil-works/pi-coding-agent':'1.0.0','fs-native-extensions':'1.5.1'}}));
  console.log('Consumer install: exact SDK/native pins; independent transitive resolution, scripts disabled.');
  run('npm',['install','--ignore-scripts','--no-audit','--no-fund'],consumer);
  copyFileSync(new URL(import.meta.url),join(consumer,'probe.mjs'));
  console.log(run(process.execPath,['probe.mjs'],consumer));
  process.exit(0);
}
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
const consumer=process.cwd(); const require=createRequire(path.join(consumer,'package.json'));
const packageRoot=path.dirname(require.resolve('gentle-pi/package.json'));
const owned = file => { assert.ok(fs.realpathSync(file).startsWith(fs.realpathSync(path.join(consumer,'node_modules'))+path.sep), 'dependency must resolve inside installed consumer: '+file); return file; };
const packedRequire=createRequire(path.join(packageRoot,'package.json'));
const nativePath=owned(packedRequire.resolve('fs-native-extensions'));
assert.equal(packedRequire('fs-native-extensions/package.json').version,'1.5.1');
const sdkEntry=owned(fileURLToPath(import.meta.resolve('@earendil-works/pi-coding-agent')));
assert.equal(JSON.parse(fs.readFileSync(path.join(consumer,'node_modules/@earendil-works/pi-coding-agent/package.json'),'utf8')).version,'1.0.0');
const sdkRequire=createRequire(sdkEntry); const jitiPath=owned(sdkRequire.resolve('jiti'));
const { createJiti }=await import(pathToFileURL(jitiPath).href);
const jiti=createJiti(pathToFileURL(path.join(consumer,'package.json')).href,{moduleCache:false});
const {tryNativeFileLock,releaseNativeFileLock}=await jiti.import(path.join(packageRoot,'lib/native-file-lock.ts'));
const lock=path.join(process.env.TEMP,'packed-native.lock');
const fd=tryNativeFileLock(lock); assert.notEqual(fd,undefined);assert.equal(tryNativeFileLock(lock),undefined);releaseNativeFileLock(fd);
const sdk=await import(pathToFileURL(sdkEntry).href);
const extensionPath=path.join(packageRoot,'extensions/gentle-ai.ts');
const loaded=await sdk.discoverAndLoadExtensions([extensionPath],consumer,process.env.PI_CODING_AGENT_DIR);
assert.deepEqual(loaded.errors,[]);assert.equal(loaded.extensions.length,1);
const ext=loaded.extensions[0];assert.ok(ext.commands.has('gentle:models'));assert.ok(ext.handlers.has('session_start'));
const home=process.env.GENTLE_PI_AGENT_HOME;
const agentPath=path.join(home,'agents','worker.md');fs.writeFileSync(agentPath,'---\nname: worker\ndescription: Worker\n---\nbody\n');
const routePath=path.join(home,'subagents.json');fs.writeFileSync(routePath,JSON.stringify({max_concurrency:3,model_profiles:{outsider:{model:'openai/user'}}}));
const notices=[];let config={worker:{model:'openai/packed',thinking:'high'}};
const ctx={cwd:consumer,hasUI:true,sessionManager:{getSessionId:()=> 'packed-proof',getSessionFile:()=>path.join(consumer,'session.jsonl')},modelRegistry:{getAvailable:async()=>[]},ui:{notify:(message)=>notices.push(message),custom:async()=>({type:'save',config}),confirm:async()=>true}};
await ext.commands.get('gentle:models').handler('',ctx);
assert.deepEqual(JSON.parse(fs.readFileSync(routePath,'utf8')).model_profiles.worker,{model:'openai/packed',effort:'high'});
assert.match(fs.readFileSync(agentPath,'utf8'),/^model: openai\/packed$/m);assert.match(fs.readFileSync(agentPath,'utf8'),/^thinking: high$/m);
const tracking=path.join(home,'gentle-ai','materialized-model-profiles.json');
assert.deepEqual(JSON.parse(fs.readFileSync(tracking,'utf8')).agents,['worker']);const inode=fs.statSync(tracking+'.lock').ino;
assert.ok(notices.some(n=>n.includes('Agents updated: 2')));
const modelModule=await jiti.import(extensionPath);
fs.writeFileSync(path.join(process.env.GENTLE_PI_CONFIG_HOME,'models.json'),JSON.stringify({worker:{}}));
assert.deepEqual(await modelModule.applySavedModelConfig(ctx),{updated:2,skipped:0});
assert.doesNotMatch(fs.readFileSync(agentPath,'utf8'),/^(model|thinking):/m);
const routes=JSON.parse(fs.readFileSync(routePath,'utf8'));assert.equal('worker' in routes.model_profiles,false);assert.equal(routes.max_concurrency,3);assert.deepEqual(routes.model_profiles.outsider,{model:'openai/user'});assert.equal(fs.statSync(tracking+'.lock').ino,inode);
config={worker:{}};await ext.commands.get('gentle:models').handler('',ctx);
const nativeBindings=Object.keys(packedRequire.cache).filter(p=>p.endsWith('.node') && p.includes('fs-native-extensions')).map(p=>fs.realpathSync(p));
assert.equal(nativeBindings.length,1);
assert.equal(nativeBindings[0],fs.realpathSync(path.join(path.dirname(nativePath),`prebuilds/${process.platform}-${process.arch}/fs-native-extensions.node`)));
console.log(JSON.stringify({pass:true,sourceCommit:process.env.PROOF_COMMIT,tarballSha256:process.env.PROOF_SHA256,sdk:'1.0.0',native:'1.5.1',nativePath,sdkEntry,jitiPath,nativeBindings,platform:process.platform,arch:process.arch,node:process.version,loader:'public SDK discoverAndLoadExtensions/Jiti',assertions:{noLoadErrors:true,registeredModelSave:true,routing:true,markdown:true,ownership:true,startupClearCounters:true,unrelatedKeysPreserved:true,permanentInode:true,descriptorExclusion:true,parentDependencyFallback:false},consumerTransitives:'independently resolved; npm package-lock.json in consumer'}));
